version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=development
      - APP_PORT=3333
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - STORAGE_DRIVER=disk
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
